
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getClientOptions } from './config';

const SUPABASE_URL = "https://ptkqosrcopnsclgyrjqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0a3Fvc3Jjb3Buc2NsZ3lyanFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Nzg2MzUsImV4cCI6MjA1OTU1NDYzNX0.02iDkud89OEj98hFFkOt8_QNhs_N6uqAXj4laoZi7Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the Supabase client with options
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  getClientOptions()
);

// Re-export utility functions from separate modules
export { 
  snakeToCamel, 
  camelToSnake 
} from './utils/formatUtils';

export { 
  increment, 
  decrement 
} from './utils/counterUtils';

export { 
  insertIntoTable,
  updateTable,
  batchSaveToTable,
  TableName
} from './utils/tableUtils';

export { 
  addToDeletedCache, 
  isInDeletedCache,
  removeFromDeletedCache,
  filterDeletedItems
} from './utils/cacheUtils';

export {
  getClientTotalSpent,
  getSupplierTotalSpent
} from './utils/financialUtils';

export {
  countPendingOrders,
  getLowStockProducts
} from './utils/queryUtils';
